# Generated by Django 2.0.6 on 2018-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0003_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
