# Generated by Django 2.0.6 on 2018-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0004_auto_20180816_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
